name: Plugin Check + SonarQube + Deploy WordPress

on:
  push:
    tags:
      - "v*"

jobs:
  check-sonar-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout plugin code
        uses: actions/checkout@v4

      - name: Set up PHP 8.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install WP-CLI and run basic plugin check
        run: |
          curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
          chmod +x wp-cli.phar
          sudo mv wp-cli.phar /usr/local/bin/wp
          wp --info
          echo "✅ WP-CLI instalado. Plugin listo para el escaneo."

      - name: Run SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v2.0.2
        with:
          projectBaseDir: .
          args: |
            -Dsonar.projectKey=wp-utils
            -Dsonar.projectName=WP_Utils
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Prepare clean plugin-dist folder (exclude .scannerwork and others)
        run: |
          mkdir plugin-dist
          rsync -av \
            --exclude='.git*' \
            --exclude='.github' \
            --exclude='.scannerwork' \
            --exclude='plugin-dist' \
            --exclude='tests' \
            --exclude='composer.*' \
            --exclude='node_modules' \
            --exclude='package*' \
            ./ ./plugin-dist/

      - name: Checkout WordPress.org SVN repo
        run: |
          svn checkout https://plugins.svn.wordpress.org/wp-utils/ svn \
            --username "${{ secrets.SVN_USERNAME }}" \
            --password "${{ secrets.SVN_PASSWORD }}" \
            --non-interactive

      - name: Copy clean files to SVN trunk
        run: |
          rm -rf svn/trunk/*
          cp -R plugin-dist/* svn/trunk/

      - name: Deploy to WordPress.org
        uses: nk-o/action-wordpress-plugin-deploy@master
        with:
          plugin-dir: svn/trunk
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SLUG: wp-utils
